# AX45MPV RVV Core — Synthesis Filelist
# Top: RvvCoreMiniAxi | VLEN=DLEN=512 | Target: 2GHz
# Generated: Wed Jun 10 04:19:50 PM HKT 2026

+define+USE_GENERIC
+define+VLEN_512
+define+ZVE32F_ON
+define+VLEN=512
+define+VLENB=64
+define+VLENH=32
+define+VLENW=16
+define+DLEN=512
+define+FLEN=32
+define+XLEN=32

+incdir+third_party/ax45mpv/andes_ip/kv_core/top/hdl
+incdir+third_party/ax45mpv/andes_ip/kv_core/vpu/hdl
+incdir+third_party/ax45mpv/andes_ip/kv_core/ucore/hdl
+incdir+third_party/ax45mpv/andes_ip/kv_core/macro/hdl
+incdir+third_party/ax45mpv/andes_ip/macro
+incdir+hdl/verilog/rvv/inc

# ---- Top-level RTL ----
bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMiniAxi.sv

# ---- Donor RTL (222 files) ----
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_sint_to_fp_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_sint_to_fp.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vagu.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_adder71.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_lane_top.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_shifter.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_veq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_vrf_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_valu_wb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vcmt_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vcmt_dis.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vcmt.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vcompress_idx.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vcompress_slice.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vconn.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vconn_vs.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdec.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdis.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv64.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv_adder71.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv_if.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv_op.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vdiv_wb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_dlen.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_elen.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_veq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_vrf_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfdiv_wb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmac_elen32.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmac_elen64.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmac_lane_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmac_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_elen.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_lane_top_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_lane_top.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_veq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_vrf_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfmis_wb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fdiv_dsu.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fdiv.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fmac16.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fmac64.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fmac.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vfp_fmis.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vimac_lane_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vimac_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_viq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_addrq_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_align_rbuf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_align_wbuf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_buf_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_buf_info_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_cross_check.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_element_dec.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_element_remap.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_gen_buf_info_hvm.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_gen_bwe.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_gen_mask.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_gen_ones.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_hr_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_hr.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_packed_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_packed_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vlsq_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vlsq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_seg_dict.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_seg_num.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_seg_xptr.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_total_element_num.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_unpacked_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_unpacked_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_uop_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_uop.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_ustride_unpacked.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vlsu.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_v0t_dlen.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_vs2q.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vls_xcpt_dec.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_lane_top_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_lane_top.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_veq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_vrf_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmac_wb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmask.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vmask_ve0.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpermut_idx.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpermut_pu.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpermut.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpu_lane_top.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpu_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpu_lane_xl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpu_pipe.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vpu.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrf_mem.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrf_read_pipe.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrf_rport.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrf_wport.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrgatherei16_idx_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vrgather_idx_lane.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vscb_age_next.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vscb_portmap.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vscb.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vscb_vx_cmp.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vscb_vx.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_beat.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_cp_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_eb_bypass.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_eb_pipelined.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_merge_buf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_sizedn.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_sizeup.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_srf_ld_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_st_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_stub.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_veq.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_vrf_ld_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsp_vs_ctrl.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vsrf.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vtlb_ent.v
third_party/ax45mpv/andes_ip/kv_core/vpu/hdl/kv_vtlb.v
third_party/ax45mpv/andes_ip/kv_core/ucore/hdl/kv_ace_predec.v
third_party/ax45mpv/andes_ip/kv_core/ucore/hdl/kv_pma2axcache.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_add_one.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_arb_fp_mb.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_arb_fp.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_arb_qos3.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_arb_rr_mb.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_arb_rr.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_async_fifo.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_axi_m_buffer.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_bin2onehot.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_bit_expand.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_bit_reverse.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_clkdiv.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_cnt_johnson.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_cnt_onehot.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_cnt_scnto.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_csb.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_dff_bwe_rar.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_dff_bwe.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_dff_gen_rar.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_dff_gen.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eb_bypass.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eb_full_i.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eb_full_o.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eb_half.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eb_pipelined.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eccdec32.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eccdec64.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eccenc32.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_eccenc64.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_fasthit.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_ffs.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_fifo1.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_fifon.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_fifo.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_fls.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_minmax.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux128.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux16.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux32.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux64.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux8.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_muxn_onehot.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_muxn.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux_onehot.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_mux.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_nooverflow_add.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_nounderflow_sub.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_novf_adder_op3.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_one_ext.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_onehot2bin.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_onehot.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_pardec32.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_pardec64.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_parenc32.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_parenc64.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_plru_ent.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_plru.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_sign_ext.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_stall_filter.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_sync_l2l.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_vor.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_zdb.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/kv_zero_ext.v
third_party/ax45mpv/andes_ip/kv_core/macro/hdl/sample_kv_clk_gen.v
third_party/ax45mpv/andes_ip/kv_core/ace/hdl/ace_pre_dec.v
third_party/ax45mpv/andes_ip/kv_core/ace/hdl/ace.v
third_party/ax45mpv/andes_ip/kv_core/ace/hdl/vace_dec.v
third_party/ax45mpv/andes_ip/kv_core/ace/hdl/vace.v
third_party/ax45mpv/andes_ip/kv_core/biu/hdl/kv_biu.v
third_party/ax45mpv/andes_ip/kv_core/tilelink/hdl/kv_tl_beat_cnt.v
third_party/ax45mpv/andes_ip/kv_core/tilelink/hdl/kv_tlc_mux.v
third_party/ax45mpv/andes_ip/kv_core/tilelink/hdl/kv_tlu_demux.v
third_party/ax45mpv/andes_ip/kv_core/tilelink/hdl/kv_tlul_sizeup.v
third_party/ax45mpv/andes_ip/kv_core/tilelink/hdl/kv_tlu_sizeup.v
third_party/ax45mpv/andes_ip/kv_core/fpu/hdl/kv_csa3_2.v
third_party/ax45mpv/andes_ip/kv_core/fpu/hdl/kv_lzc_encode.v
third_party/ax45mpv/andes_ip/macro/nds_lib.v
hdl/verilog/rvv/inc/rvv_backend_alu.svh
hdl/verilog/rvv/inc/rvv_backend_config.svh
hdl/verilog/rvv/inc/rvv_backend_define.svh
hdl/verilog/rvv/inc/rvv_backend_dispatch.svh
hdl/verilog/rvv/inc/rvv_backend_div.svh
hdl/verilog/rvv/inc/rvv_backend_fma.svh
hdl/verilog/rvv/inc/rvv_backend_pmtrdt.svh
hdl/verilog/rvv/inc/rvv_backend_sva.svh
hdl/verilog/rvv/inc/rvv_backend.svh
