`define EMLUNIT_SV
// Generated by CIRCT firtool-1.62.1
module FP32Multiplier(
  input  [31:0] io_a,
                io_b,
  output [31:0] io_result
);

  wire        aIsZero = io_a[30:23] == 8'h0 & ~(|(io_a[22:0]));
  wire        bIsZero = io_b[30:23] == 8'h0 & ~(|(io_b[22:0]));
  wire [47:0] man48 = {24'h0, ~aIsZero, io_a[22:0]} * {24'h0, ~bIsZero, io_b[22:0]};
  wire [7:0]  _exp10_T_4 = io_a[30:23] + io_b[30:23] - 8'h7F;
  wire [7:0]  expNorm = man48[47] ? _exp10_T_4 + 8'h1 : _exp10_T_4;
  wire [22:0] manShifted = man48[47] ? man48[46:24] : man48[45:23];
  wire [23:0] _manRounded_T_5 =
    {1'h0, manShifted}
    + {23'h0,
       (man48[47] ? man48[23] : man48[22])
         & ((man48[47] ? (|(man48[22:0])) : (|(man48[21:0]))) | manShifted[0])};
  wire [7:0]  expFinal =
    _manRounded_T_5[23] ? ((&expNorm) ? 8'hFF : expNorm + 8'h1) : expNorm;
  wire        _GEN = (&(io_a[30:23])) & ~(|(io_a[22:0]));
  wire        _GEN_0 = (&(io_b[30:23])) & ~(|(io_b[22:0]));
  assign io_result =
    (&(io_a[30:23])) & (|(io_a[22:0])) | (&(io_b[30:23])) & (|(io_b[22:0])) | _GEN
    & bIsZero | _GEN_0 & aIsZero
      ? 32'h7F800001
      : {io_a[31] ^ io_b[31],
         _GEN | _GEN_0
           ? 31'h7F800000
           : aIsZero | bIsZero
               ? 31'h0
               : (&expFinal)
                   ? 31'h7F800000
                   : {expFinal, _manRounded_T_5[23] ? 23'h0 : _manRounded_T_5[22:0]}};
endmodule

module FP32Adder(
  input  [31:0] io_a,
                io_b,
  output [31:0] io_result
);

  wire        aIsZero = io_a[30:23] == 8'h0 & ~(|(io_a[22:0]));
  wire        bIsZero = io_b[30:23] == 8'h0 & ~(|(io_b[22:0]));
  wire [23:0] mAext_hi = {~aIsZero, io_a[22:0]};
  wire [23:0] mBext_hi = {~bIsZero, io_b[22:0]};
  wire        swap =
    io_a[30:23] < io_b[30:23] | io_a[30:23] == io_b[30:23]
    & {~aIsZero, io_a[22:0]} < {~bIsZero, io_b[22:0]};
  wire        sL = swap ? io_b[31] : io_a[31];
  wire [7:0]  eL = swap ? io_b[30:23] : io_a[30:23];
  wire [7:0]  _expDiff_T = eL - (swap ? io_a[30:23] : io_b[30:23]);
  wire [27:0] _GEN = {1'h0, swap ? mBext_hi : mAext_hi, 3'h0};
  wire [27:0] _GEN_0 =
    {1'h0,
     {swap ? mAext_hi : mBext_hi, 3'h0} >> (_expDiff_T > 8'h1B ? 8'h1B : _expDiff_T)};
  wire [27:0] manSum = sL == (swap ? io_a[31] : io_b[31]) ? _GEN + _GEN_0 : _GEN - _GEN_0;
  wire [3:0]  _GEN_1 =
    {{manSum[5:4], manSum[7]} & 3'h5, 1'h0} | {manSum[7:6], manSum[9:8]} & 4'h5;
  wire [4:0]  leadingZeros =
    manSum[26]
      ? 5'h0
      : manSum[25]
          ? 5'h1
          : manSum[24]
              ? 5'h2
              : manSum[23]
                  ? 5'h3
                  : manSum[22]
                      ? 5'h4
                      : manSum[21]
                          ? 5'h5
                          : manSum[20]
                              ? 5'h6
                              : manSum[19]
                                  ? 5'h7
                                  : manSum[18]
                                      ? 5'h8
                                      : manSum[17]
                                          ? 5'h9
                                          : manSum[16]
                                              ? 5'hA
                                              : manSum[15]
                                                  ? 5'hB
                                                  : manSum[14]
                                                      ? 5'hC
                                                      : manSum[13]
                                                          ? 5'hD
                                                          : manSum[12]
                                                              ? 5'hE
                                                              : manSum[11]
                                                                  ? 5'hF
                                                                  : manSum[10]
                                                                      ? 5'h10
                                                                      : manSum[9]
                                                                          ? 5'h11
                                                                          : _GEN_1[0]
                                                                              ? 5'h12
                                                                              : _GEN_1[1]
                                                                                  ? 5'h13
                                                                                  : _GEN_1[2]
                                                                                      ? 5'h14
                                                                                      : _GEN_1[3]
                                                                                          ? 5'h15
                                                                                          : manSum[4]
                                                                                              ? 5'h16
                                                                                              : manSum[3]
                                                                                                  ? 5'h17
                                                                                                  : manSum[2]
                                                                                                      ? 5'h18
                                                                                                      : manSum[1]
                                                                                                          ? 5'h19
                                                                                                          : 5'h1A;
  wire        _GEN_2 = manSum == 28'h0;
  wire [57:0] _normMant_T_2 = {31'h0, manSum[26:0]} << leadingZeros;
  wire [25:0] normMant = _GEN_2 ? 26'h0 : manSum[27] ? manSum[26:1] : _normMant_T_2[25:0];
  wire [7:0]  normExp =
    _GEN_2 ? 8'h0 : manSum[27] ? eL + 8'h1 : eL - {3'h0, leadingZeros};
  wire [23:0] _manRounded_T_2 =
    {1'h0, normMant[25:3]} + {23'h0, normMant[2] & ((|(normMant[1:0])) | normMant[3])};
  wire [7:0]  expFinal =
    _manRounded_T_2[23] ? ((&normExp) ? 8'hFF : normExp + 8'h1) : normExp;
  wire        _GEN_3 = (&(io_a[30:23])) & ~(|(io_a[22:0]));
  wire        _GEN_4 = (&(io_b[30:23])) & ~(|(io_b[22:0]));
  assign io_result =
    (&(io_a[30:23])) & (|(io_a[22:0])) | (&(io_b[30:23])) & (|(io_b[22:0])) | _GEN_3
    & _GEN_4 & io_a[31] != io_b[31]
      ? 32'h7F800001
      : _GEN_3
          ? io_a
          : _GEN_4
              ? io_b
              : aIsZero & bIsZero
                  ? 32'h0
                  : aIsZero
                      ? io_b
                      : bIsZero
                          ? io_a
                          : _GEN_2
                              ? 32'h0
                              : {sL,
                                 (&expFinal)
                                   ? 31'h7F800000
                                   : {expFinal,
                                      _manRounded_T_2[23]
                                        ? 23'h0
                                        : _manRounded_T_2[22:0]}};
endmodule

module ExpApprox(
  input         clock,
  input  [31:0] io_operand,
  output [31:0] io_result
);

  wire [31:0]        _addInterp_io_result;
  wire [31:0]        _mulInterp_io_result;
  wire [31:0]        _subDiff_io_result;
  wire [31:0]        _subFrac_io_result;
  wire [31:0]        _mulNorm_io_result;
  wire [31:0]        _addBias_io_result;
  wire [31:0]        _subR_io_result;
  wire [31:0]        _mulKLn2_io_result;
  wire [31:0]        _mulInvLn2_io_result;
  wire [127:0][31:0] _GEN =
    '{32'h3FB504F3,
      32'h3FB408B8,
      32'h3FB30DDB,
      32'h3FB2145D,
      32'h3FB11C3A,
      32'h3FB02570,
      32'h3FAF2FFF,
      32'h3FAE3BE4,
      32'h3FAD491C,
      32'h3FAC57A7,
      32'h3FAB6783,
      32'h3FAA78AD,
      32'h3FA98B24,
      32'h3FA89EE6,
      32'h3FA7B3F1,
      32'h3FA6CA43,
      32'h3FA5E1DB,
      32'h3FA4FAB7,
      32'h3FA414D5,
      32'h3FA33034,
      32'h3FA24CD0,
      32'h3FA16AAA,
      32'h3FA089BF,
      32'h3F9FAA0D,
      32'h3F9ECB93,
      32'h3F9DEE4F,
      32'h3F9D123F,
      32'h3F9C3762,
      32'h3F9B5DB6,
      32'h3F9A8539,
      32'h3F99ADEA,
      32'h3F98D7C7,
      32'h3F9802CE,
      32'h3F972EFE,
      32'h3F965C55,
      32'h3F958AD2,
      32'h3F94BA72,
      32'h3F93EB35,
      32'h3F931D19,
      32'h3F92501C,
      32'h3F91843C,
      32'h3F90B979,
      32'h3F8FEFD0,
      32'h3F8F2740,
      32'h3F8E5FC8,
      32'h3F8D9965,
      32'h3F8CD417,
      32'h3F8C0FDC,
      32'h3F8B4CB2,
      32'h3F8A8A98,
      32'h3F89C98D,
      32'h3F89098F,
      32'h3F884A9C,
      32'h3F878CB3,
      32'h3F86CFD3,
      32'h3F8613FA,
      32'h3F855927,
      32'h3F849F58,
      32'h3F83E68C,
      32'h3F832EC2,
      32'h3F8277F8,
      32'h3F81C22C,
      32'h3F810D5E,
      32'h3F80598B,
      32'h3F7F4D67,
      32'h3F7DE9A9,
      32'h3F7C87DC,
      32'h3F7B27FB,
      32'h3F79CA05,
      32'h3F786DF6,
      32'h3F7713CD,
      32'h3F75BB85,
      32'h3F74651E,
      32'h3F731093,
      32'h3F71BDE3,
      32'h3F706D0B,
      32'h3F6F1E08,
      32'h3F6DD0D9,
      32'h3F6C8579,
      32'h3F6B3BE7,
      32'h3F69F420,
      32'h3F68AE22,
      32'h3F6769EB,
      32'h3F662777,
      32'h3F64E6C4,
      32'h3F63A7D0,
      32'h3F626A99,
      32'h3F612F1C,
      32'h3F5FF556,
      32'h3F5EBD46,
      32'h3F5D86E8,
      32'h3F5C523B,
      32'h3F5B1F3C,
      32'h3F59EDE8,
      32'h3F58BE3E,
      32'h3F57903C,
      32'h3F5663DE,
      32'h3F553922,
      32'h3F541007,
      32'h3F52E88A,
      32'h3F51C2A9,
      32'h3F509E61,
      32'h3F4F7BB0,
      32'h3F4E5A94,
      32'h3F4D3B0C,
      32'h3F4C1D13,
      32'h3F4B00AA,
      32'h3F49E5CC,
      32'h3F48CC79,
      32'h3F47B4AE,
      32'h3F469E69,
      32'h3F4589A7,
      32'h3F447667,
      32'h3F4364A7,
      32'h3F425464,
      32'h3F41459C,
      32'h3F40384E,
      32'h3F3F2C77,
      32'h3F3E2215,
      32'h3F3D1926,
      32'h3F3C11A9,
      32'h3F3B0B9A,
      32'h3F3A06F9,
      32'h3F3903C3,
      32'h3F3801F6,
      32'h3F370191,
      32'h3F360290,
      32'h3F3504F3};
  reg  [31:0]        s0_x;
  reg  [31:0]        s1_x;
  reg  [31:0]        s1_mulInvLn2;
  reg  [31:0]        s2_x;
  reg  [31:0]        s2_k;
  reg  [31:0]        s2_kFp;
  reg  [31:0]        s3_r;
  reg  [31:0]        s3_k;
  reg  [31:0]        s4_mulNorm;
  reg  [31:0]        s4_k;
  reg  [31:0]        s5_lut0;
  reg  [31:0]        s5_frac;
  reg  [31:0]        s5_diff;
  reg  [31:0]        s5_k;
  reg  [31:0]        s6_interp;
  reg  [31:0]        s6_lut0;
  reg  [31:0]        s6_k;
  reg  [31:0]        resultReg;
  reg                s0_isNaN;
  reg                s0_isPosInf;
  reg                s0_isNegInf;
  reg                s1_isNaN;
  reg                s1_isPosInf;
  reg                s1_isNegInf;
  reg                s2_isNaN;
  reg                s2_isPosInf;
  reg                s2_isNegInf;
  reg                s3_isNaN;
  reg                s3_isPosInf;
  reg                s3_isNegInf;
  reg                s4_isNaN;
  reg                s4_isPosInf;
  reg                s4_isNegInf;
  reg                s5_isNaN;
  reg                s5_isPosInf;
  reg                s5_isNegInf;
  reg                s6_isNaN;
  reg                s6_isPosInf;
  reg                s6_isNegInf;
  wire [9:0]         _GEN_0 = {2'h0, s4_mulNorm[30:23]};
  wire [9:0]         _eUnbAddr_T_2 = _GEN_0 - 10'h7F;
  wire [1046:0]      _rnInt_T_7 = {1024'h1, s4_mulNorm[22:0]} << _GEN_0 - 10'h96;
  wire [31:0]        rnInt =
    s4_mulNorm[30:23] == 8'h0 | $signed(_eUnbAddr_T_2) < 10'sh0
      ? 32'h0
      : $signed(_eUnbAddr_T_2) < 10'sh17
          ? {8'h0, {1'h1, s4_mulNorm[22:0]} >> 10'h17 - _eUnbAddr_T_2}
          : $signed(_eUnbAddr_T_2) < 10'sh1F ? _rnInt_T_7[31:0] : 32'h7F;
  wire [6:0]         addrFull = (|(rnInt[31:7])) ? 7'h7F : rnInt[6:0];
  wire [6:0]         _GEN_1 = addrFull & 7'h30;
  wire [2:0]         _GEN_2 = {addrFull[6], 2'h0} | _GEN_1[2:0];
  wire [2:0]         _GEN_3 = _GEN_2 & 3'h2;
  wire [4:0]         _addrFp32_lz_T_90 =
    _GEN_3[0]
      ? 5'h15
      : _GEN_2[1]
          ? 5'h16
          : _GEN_3[2] | _GEN_2[0]
              ? 5'h17
              : _GEN_2[2]
                  ? 5'h19
                  : addrFull[5]
                      ? 5'h1A
                      : addrFull[4]
                          ? 5'h1B
                          : addrFull[3]
                              ? 5'h1C
                              : addrFull[2] | _GEN_1[6] ? 5'h1D : {4'hF, ~(addrFull[1])};
  wire               _addrFp32_man_T = addrFull == 7'h0;
  wire [62:0]        _addrFp32_man_T_1 = {56'h0, addrFull} << _addrFp32_lz_T_90;
  always @(posedge clock) begin
    automatic logic [9:0]    _GEN_4 = {2'h0, s1_mulInvLn2[30:23]};
    automatic logic [9:0]    _eUnbK_T_2 = _GEN_4 - 10'h7F;
    automatic logic [23:0]   manExt = {1'h1, s1_mulInvLn2[22:0]};
    automatic logic          _GEN_5 = s1_mulInvLn2[30:23] == 8'h0;
    automatic logic          _GEN_6 = $signed(_eUnbK_T_2) < 10'sh0;
    automatic logic          _GEN_7 = $signed(_eUnbK_T_2) < 10'sh17;
    automatic logic [9:0]    _shiftR_T = 10'h17 - _eUnbK_T_2;
    automatic logic [23:0]   _roundUp_T_3 = manExt >> _shiftR_T - 10'h1;
    automatic logic [1046:0] _absVal_T_4 =
      {1024'h1, s1_mulInvLn2[22:0]} << _GEN_4 - 10'h96;
    automatic logic [31:0]   _absRounded_T =
      (_GEN_5 | _GEN_6 ? 32'h0 : _GEN_7 ? {8'h0, manExt >> _shiftR_T} : _absVal_T_4[31:0])
      + {31'h0, ~_GEN_5 & (_GEN_6 ? (&_eUnbK_T_2) : _GEN_7 & _roundUp_T_3[0])};
    automatic logic [31:0]   intVal =
      s1_mulInvLn2[31] ? 32'h0 - _absRounded_T : _absRounded_T;
    automatic logic          _s2_kFp_T = $signed(intVal) < 32'sh0;
    automatic logic [31:0]   absK = _s2_kFp_T ? 32'h0 - intVal : intVal;
    automatic logic [7:0]    _GEN_8 =
      {{absK[11:8], absK[15:14]} & 6'h33, 2'h0} | {absK[15:12], absK[19:16]} & 8'h33;
    automatic logic [18:0]   _GEN_9 =
      {absK[5:4], absK[7:6], absK[9:8], _GEN_8, absK[19:18], absK[21:20], absK[23]}
      & 19'h55555;
    automatic logic [3:0]    _GEN_10 = _GEN_9[18:15] | {absK[7:6], absK[9:8]} & 4'h5;
    automatic logic [7:0]    _GEN_11 = _GEN_9[14:7] | _GEN_8 & 8'h55;
    automatic logic [3:0]    _GEN_12 =
      {_GEN_9[2:0], 1'h0} | {absK[23:22], absK[25:24]} & 4'h5;
    automatic logic [4:0]    s2_kFp_lz =
      absK[31]
        ? 5'h0
        : absK[30]
            ? 5'h1
            : absK[29]
                ? 5'h2
                : absK[28]
                    ? 5'h3
                    : absK[27]
                        ? 5'h4
                        : absK[26]
                            ? 5'h5
                            : absK[25]
                                ? 5'h6
                                : _GEN_12[0]
                                    ? 5'h7
                                    : _GEN_12[1]
                                        ? 5'h8
                                        : _GEN_12[2]
                                            ? 5'h9
                                            : _GEN_12[3]
                                                ? 5'hA
                                                : absK[20]
                                                    ? 5'hB
                                                    : absK[19]
                                                        ? 5'hC
                                                        : _GEN_9[5] | absK[18]
                                                            ? 5'hD
                                                            : _GEN_8[1]
                                                                ? 5'hE
                                                                : _GEN_11[0]
                                                                    ? 5'hF
                                                                    : _GEN_11[1]
                                                                        ? 5'h10
                                                                        : _GEN_11[2]
                                                                            ? 5'h11
                                                                            : _GEN_11[3]
                                                                                ? 5'h12
                                                                                : _GEN_11[4]
                                                                                    ? 5'h13
                                                                                    : _GEN_11[5]
                                                                                        ? 5'h14
                                                                                        : _GEN_11[6]
                                                                                            ? 5'h15
                                                                                            : _GEN_11[7]
                                                                                                ? 5'h16
                                                                                                : _GEN_10[0]
                                                                                                    ? 5'h17
                                                                                                    : _GEN_10[1]
                                                                                                        ? 5'h18
                                                                                                        : _GEN_10[2]
                                                                                                            ? 5'h19
                                                                                                            : _GEN_10[3]
                                                                                                                ? 5'h1A
                                                                                                                : absK[4]
                                                                                                                    ? 5'h1B
                                                                                                                    : absK[3]
                                                                                                                        ? 5'h1C
                                                                                                                        : absK[2]
                                                                                                                            ? 5'h1D
                                                                                                                            : {4'hF,
                                                                                                                               ~(absK[1])};
    automatic logic          _s2_kFp_man_T = absK == 32'h0;
    automatic logic [31:0]   _newExp_T_2 = {24'h0, _addInterp_io_result[30:23]} + s6_k;
    automatic logic          _GEN_13 = $signed(_newExp_T_2) < 32'sh0;
    automatic logic          _GEN_14 = $signed(_newExp_T_2) > 32'shFF;
    automatic logic [62:0]   _s2_kFp_man_T_1 = {31'h0, absK} << s2_kFp_lz;
    s0_x <= io_operand;
    s1_x <= s0_x;
    s1_mulInvLn2 <= _mulInvLn2_io_result;
    s2_x <= s1_x;
    s2_k <= intVal;
    s2_kFp <=
      {_s2_kFp_T,
       _s2_kFp_man_T ? 8'h0 : 8'h9E - {3'h0, s2_kFp_lz},
       _s2_kFp_man_T ? 23'h0 : _s2_kFp_man_T_1[30:8]};
    s3_r <= _subR_io_result;
    s3_k <= s2_k;
    s4_mulNorm <= _mulNorm_io_result;
    s4_k <= s3_k;
    s5_lut0 <= _GEN[addrFull];
    s5_frac <= _subFrac_io_result;
    s5_diff <= _subDiff_io_result;
    s5_k <= s4_k;
    s6_interp <= _mulInterp_io_result;
    s6_lut0 <= s5_lut0;
    s6_k <= s5_k;
    resultReg <=
      s6_isNaN
        ? 32'h7F800001
        : s6_isPosInf
            ? 32'h7F800000
            : s6_isNegInf
                ? 32'h0
                : {_addInterp_io_result[31],
                   _GEN_13 ? 8'h0 : _GEN_14 ? 8'hFF : _newExp_T_2[7:0],
                   _GEN_13 | _GEN_14 ? 23'h0 : _addInterp_io_result[22:0]};
    s0_isNaN <= (&(io_operand[30:23])) & (|(io_operand[22:0]));
    s0_isPosInf <= (&(io_operand[30:23])) & ~(|(io_operand[22:0])) & ~(io_operand[31]);
    s0_isNegInf <= (&(io_operand[30:23])) & ~(|(io_operand[22:0])) & io_operand[31];
    s1_isNaN <= s0_isNaN;
    s1_isPosInf <= s0_isPosInf;
    s1_isNegInf <= s0_isNegInf;
    s2_isNaN <= s1_isNaN;
    s2_isPosInf <= s1_isPosInf;
    s2_isNegInf <= s1_isNegInf;
    s3_isNaN <= s2_isNaN;
    s3_isPosInf <= s2_isPosInf;
    s3_isNegInf <= s2_isNegInf;
    s4_isNaN <= s3_isNaN;
    s4_isPosInf <= s3_isPosInf;
    s4_isNegInf <= s3_isNegInf;
    s5_isNaN <= s4_isNaN;
    s5_isPosInf <= s4_isPosInf;
    s5_isNegInf <= s4_isNegInf;
    s6_isNaN <= s5_isNaN;
    s6_isPosInf <= s5_isPosInf;
    s6_isNegInf <= s5_isNegInf;
  end // always @(posedge)
  FP32Multiplier mulInvLn2 (
    .io_a      (s0_x),
    .io_b      (32'h3FB8AA3B),
    .io_result (_mulInvLn2_io_result)
  );
  FP32Multiplier mulKLn2 (
    .io_a      (s2_kFp),
    .io_b      (32'h3F317218),
    .io_result (_mulKLn2_io_result)
  );
  FP32Adder subR (
    .io_a      (s2_x),
    .io_b      ({~(_mulKLn2_io_result[31]), _mulKLn2_io_result[30:0]}),
    .io_result (_subR_io_result)
  );
  FP32Adder addBias (
    .io_a      (s3_r),
    .io_b      (32'h3EB17218),
    .io_result (_addBias_io_result)
  );
  FP32Multiplier mulNorm (
    .io_a      (_addBias_io_result),
    .io_b      (32'h433738E7),
    .io_result (_mulNorm_io_result)
  );
  FP32Adder subFrac (
    .io_a      (s4_mulNorm),
    .io_b
      ({1'h1,
        _addrFp32_man_T ? 8'h0 : 8'h9E - {3'h0, _addrFp32_lz_T_90},
        _addrFp32_man_T ? 23'h0 : _addrFp32_man_T_1[30:8]}),
    .io_result (_subFrac_io_result)
  );
  FP32Adder subDiff (
    .io_a      (_GEN[(&addrFull) ? 7'h7F : addrFull + 7'h1]),
    .io_b      ({~(_GEN[addrFull][31]), _GEN[addrFull][30:0]}),
    .io_result (_subDiff_io_result)
  );
  FP32Multiplier mulInterp (
    .io_a      (s5_diff),
    .io_b      (s5_frac),
    .io_result (_mulInterp_io_result)
  );
  FP32Adder addInterp (
    .io_a      (s6_lut0),
    .io_b      (s6_interp),
    .io_result (_addInterp_io_result)
  );
  assign io_result = resultReg;
endmodule

module Int32ToFP32(
  input  [31:0] io_in,
  output [31:0] io_out
);

  wire        sign = $signed(io_in) < 32'sh0;
  wire [31:0] absVal = sign ? 32'h0 - io_in : io_in;
  wire [7:0]  _GEN =
    {{absVal[11:8], absVal[15:14]} & 6'h33, 2'h0} | {absVal[15:12], absVal[19:16]}
    & 8'h33;
  wire [18:0] _GEN_0 =
    {absVal[5:4],
     absVal[7:6],
     absVal[9:8],
     _GEN,
     absVal[19:18],
     absVal[21:20],
     absVal[23]} & 19'h55555;
  wire [3:0]  _GEN_1 = _GEN_0[18:15] | {absVal[7:6], absVal[9:8]} & 4'h5;
  wire [7:0]  _GEN_2 = _GEN_0[14:7] | _GEN & 8'h55;
  wire [3:0]  _GEN_3 = {_GEN_0[2:0], 1'h0} | {absVal[23:22], absVal[25:24]} & 4'h5;
  wire [4:0]  leadingZeros =
    absVal[31]
      ? 5'h0
      : absVal[30]
          ? 5'h1
          : absVal[29]
              ? 5'h2
              : absVal[28]
                  ? 5'h3
                  : absVal[27]
                      ? 5'h4
                      : absVal[26]
                          ? 5'h5
                          : absVal[25]
                              ? 5'h6
                              : _GEN_3[0]
                                  ? 5'h7
                                  : _GEN_3[1]
                                      ? 5'h8
                                      : _GEN_3[2]
                                          ? 5'h9
                                          : _GEN_3[3]
                                              ? 5'hA
                                              : absVal[20]
                                                  ? 5'hB
                                                  : absVal[19]
                                                      ? 5'hC
                                                      : _GEN_0[5] | absVal[18]
                                                          ? 5'hD
                                                          : _GEN[1]
                                                              ? 5'hE
                                                              : _GEN_2[0]
                                                                  ? 5'hF
                                                                  : _GEN_2[1]
                                                                      ? 5'h10
                                                                      : _GEN_2[2]
                                                                          ? 5'h11
                                                                          : _GEN_2[3]
                                                                              ? 5'h12
                                                                              : _GEN_2[4]
                                                                                  ? 5'h13
                                                                                  : _GEN_2[5]
                                                                                      ? 5'h14
                                                                                      : _GEN_2[6]
                                                                                          ? 5'h15
                                                                                          : _GEN_2[7]
                                                                                              ? 5'h16
                                                                                              : _GEN_1[0]
                                                                                                  ? 5'h17
                                                                                                  : _GEN_1[1]
                                                                                                      ? 5'h18
                                                                                                      : _GEN_1[2]
                                                                                                          ? 5'h19
                                                                                                          : _GEN_1[3]
                                                                                                              ? 5'h1A
                                                                                                              : absVal[4]
                                                                                                                  ? 5'h1B
                                                                                                                  : absVal[3]
                                                                                                                      ? 5'h1C
                                                                                                                      : absVal[2]
                                                                                                                          ? 5'h1D
                                                                                                                          : {4'hF,
                                                                                                                             ~(absVal[1])};
  wire [62:0] normalized = {31'h0, absVal} << leadingZeros;
  assign io_out =
    {sign,
     absVal == 32'h0
       ? 31'h0
       : {{2'h0, 6'h1F - {1'h0, leadingZeros}} + 8'h7F, normalized[30:8]}};
endmodule

module LnApprox(
  input         clock,
  input  [31:0] io_operand,
  output [31:0] io_result
);

  wire [31:0] _int2fp_io_out;
  wire [31:0] _addRecon_io_result;
  wire [31:0] _mulELn2_io_result;
  wire [31:0] _addInterp_io_result;
  wire [31:0] _mulFrac_io_result;
  wire [31:0] _subLut_io_result;
  reg  [31:0] s0_y;
  reg  [22:0] s0_man;
  reg  [8:0]  s0_exp;
  reg         s0_sign;
  reg  [31:0] s1_y;
  reg         s1_sign;
  reg  [8:0]  s1_exp;
  reg  [31:0] s1_frac;
  reg  [31:0] s1_lut0;
  reg  [31:0] s1_lut1;
  reg  [31:0] s2_y;
  reg         s2_sign;
  reg  [31:0] s2_lnM;
  reg  [31:0] s2_eLn2;
  reg  [31:0] resultReg;
  always @(posedge clock) begin
    automatic logic [127:0][31:0] _GEN =
      '{32'h3F317218,
        32'h3F306F92,
        32'h3F2F6C05,
        32'h3F2E6770,
        32'h3F2D61D1,
        32'h3F2C5B26,
        32'h3F2B536C,
        32'h3F2A4AA1,
        32'h3F2940C3,
        32'h3F2835D0,
        32'h3F2729C6,
        32'h3F261CA1,
        32'h3F250E61,
        32'h3F23FF02,
        32'h3F22EE82,
        32'h3F21DCDF,
        32'h3F20CA16,
        32'h3F1FB625,
        32'h3F1EA109,
        32'h3F1D8AC0,
        32'h3F1C7348,
        32'h3F1B5A9C,
        32'h3F1A40BC,
        32'h3F1925A4,
        32'h3F180952,
        32'h3F16EBC3,
        32'h3F15CCF3,
        32'h3F14ACE1,
        32'h3F138B89,
        32'h3F1268E9,
        32'h3F1144FE,
        32'h3F101FC4,
        32'h3F0EF938,
        32'h3F0DD159,
        32'h3F0CA821,
        32'h3F0B7D8F,
        32'h3F0A51A0,
        32'h3F09244F,
        32'h3F07F59A,
        32'h3F06C57D,
        32'h3F0593F6,
        32'h3F046100,
        32'h3F032C98,
        32'h3F01F6BB,
        32'h3F00BF65,
        32'h3EFF0D25,
        32'h3EFC9880,
        32'h3EFA20D4,
        32'h3EF7A618,
        32'h3EF52846,
        32'h3EF2A756,
        32'h3EF0233F,
        32'h3EED9BF9,
        32'h3EEB117E,
        32'h3EE883C4,
        32'h3EE5F2C3,
        32'h3EE35E72,
        32'h3EE0C6CA,
        32'h3EDE2BC1,
        32'h3EDB8D4F,
        32'h3ED8EB6A,
        32'h3ED6460A,
        32'h3ED39D25,
        32'h3ED0F0B1,
        32'h3ECE40A6,
        32'h3ECB8CFA,
        32'h3EC8D5A2,
        32'h3EC61A94,
        32'h3EC35BC7,
        32'h3EC09930,
        32'h3EBDD2C5,
        32'h3EBB087B,
        32'h3EB83A46,
        32'h3EB5681D,
        32'h3EB291F3,
        32'h3EAFB7BE,
        32'h3EACD972,
        32'h3EA9F702,
        32'h3EA71063,
        32'h3EA4258A,
        32'h3EA13668,
        32'h3E9E42F2,
        32'h3E9B4B1B,
        32'h3E984ED6,
        32'h3E954E15,
        32'h3E9248CB,
        32'h3E8F3EEB,
        32'h3E8C3065,
        32'h3E891D2C,
        32'h3E860532,
        32'h3E82E867,
        32'h3E7F8D79,
        32'h3E794046,
        32'h3E72E916,
        32'h3E6C87C9,
        32'h3E661C3E,
        32'h3E5FA655,
        32'h3E5925EC,
        32'h3E529AE0,
        32'h3E4C050E,
        32'h3E456453,
        32'h3E3EB88A,
        32'h3E38018E,
        32'h3E313F3A,
        32'h3E2A7166,
        32'h3E2397EC,
        32'h3E1CB2A2,
        32'h3E15C161,
        32'h3E0EC3FF,
        32'h3E07BA50,
        32'h3E00A428,
        32'h3DF302BA,
        32'h3DE4A37F,
        32'h3DD62A44,
        32'h3DC796AA,
        32'h3DB8E84F,
        32'h3DAA1ED2,
        32'h3D9B39CD,
        32'h3D8C38D8,
        32'h3D7A3716,
        32'h3D5BC2F3,
        32'h3D3D1469,
        32'h3D1E2A97,
        32'h3CFE092E,
        32'h3CBF42F9,
        32'h3C8000AB,
        32'h3C0080AC,
        32'h0};
    automatic logic [3:0]         _GEN_0 =
      {{s0_man[5:4], s0_man[7]} & 3'h5, 1'h0} | {s0_man[7:6], s0_man[9:8]} & 4'h5;
    automatic logic [3:0]         _leadingIndex_T =
      4'hF
      - (s0_man[15]
           ? 4'h0
           : s0_man[14]
               ? 4'h1
               : s0_man[13]
                   ? 4'h2
                   : s0_man[12]
                       ? 4'h3
                       : s0_man[11]
                           ? 4'h4
                           : s0_man[10]
                               ? 4'h5
                               : s0_man[9]
                                   ? 4'h6
                                   : _GEN_0[0]
                                       ? 4'h7
                                       : _GEN_0[1]
                                           ? 4'h8
                                           : _GEN_0[2]
                                               ? 4'h9
                                               : _GEN_0[3]
                                                   ? 4'hA
                                                   : s0_man[4]
                                                       ? 4'hB
                                                       : s0_man[3]
                                                           ? 4'hC
                                                           : s0_man[2]
                                                               ? 4'hD
                                                               : {3'h7, ~(s0_man[1])});
    automatic logic               isZero = s2_y[30:23] == 8'h0 & ~(|(s2_y[22:0]));
    automatic logic [54:0]        _normalizedFrac_T_2 =
      {39'h0, s0_man[15:0]} << 5'h17 - {1'h0, _leadingIndex_T};
    s0_y <= io_operand;
    s0_man <= io_operand[22:0];
    s0_exp <= {1'h0, io_operand[30:23]} - 9'h7F;
    s0_sign <= io_operand[31];
    s1_y <= s0_y;
    s1_sign <= s0_sign;
    s1_exp <= s0_exp;
    s1_frac <=
      s0_man[15:0] == 16'h0
        ? 32'h0
        : {1'h0, {4'h0, _leadingIndex_T} + 8'h6F, _normalizedFrac_T_2[22:0]};
    s1_lut0 <= _GEN[s0_man[22:16]];
    s1_lut1 <= _GEN[(&(s0_man[22:16])) ? 7'h7F : s0_man[22:16] + 7'h1];
    s2_y <= s1_y;
    s2_sign <= s1_sign;
    s2_lnM <= _addInterp_io_result;
    s2_eLn2 <= _mulELn2_io_result;
    resultReg <=
      (&(s2_y[30:23])) & (|(s2_y[22:0])) | s2_sign & ~isZero
        ? 32'h7F800001
        : isZero
            ? 32'hFF800000
            : (&(s2_y[30:23])) & ~(|(s2_y[22:0])) ? 32'h7F800000 : _addRecon_io_result;
  end // always @(posedge)
  FP32Adder subLut (
    .io_a      (s1_lut1),
    .io_b      ({~(s1_lut0[31]), s1_lut0[30:0]}),
    .io_result (_subLut_io_result)
  );
  FP32Multiplier mulFrac (
    .io_a      (_subLut_io_result),
    .io_b      (s1_frac),
    .io_result (_mulFrac_io_result)
  );
  FP32Adder addInterp (
    .io_a      (s1_lut0),
    .io_b      (_mulFrac_io_result),
    .io_result (_addInterp_io_result)
  );
  FP32Multiplier mulELn2 (
    .io_a      (_int2fp_io_out),
    .io_b      (32'h3F317218),
    .io_result (_mulELn2_io_result)
  );
  FP32Adder addRecon (
    .io_a      (s2_lnM),
    .io_b      (s2_eLn2),
    .io_result (_addRecon_io_result)
  );
  Int32ToFP32 int2fp (
    .io_in  ({{23{s1_exp[8]}}, s1_exp}),
    .io_out (_int2fp_io_out)
  );
  assign io_result = resultReg;
endmodule

module EMLUnit(
  input         clock,
                reset,
  input  [31:0] io_x,
                io_y,
  output [31:0] io_result
);

  wire [31:0] _lnUnit_io_result;
  wire [31:0] _expUnit_io_result;
  reg  [31:0] lnDelayed;
  reg  [31:0] lnDelayed2;
  reg  [31:0] lnDelayed3;
  reg  [31:0] lnDelayed4;
  always @(posedge clock) begin
    lnDelayed <= _lnUnit_io_result;
    lnDelayed2 <= lnDelayed;
    lnDelayed3 <= lnDelayed2;
    lnDelayed4 <= lnDelayed3;
  end // always @(posedge)
  ExpApprox expUnit (
    .clock      (clock),
    .io_operand (io_x),
    .io_result  (_expUnit_io_result)
  );
  LnApprox lnUnit (
    .clock      (clock),
    .io_operand (io_y),
    .io_result  (_lnUnit_io_result)
  );
  FP32Adder subUnit (
    .io_a      (_expUnit_io_result),
    .io_b      ({~(lnDelayed4[31]), lnDelayed4[30:0]}),
    .io_result (io_result)
  );
endmodule

